
version: 2.1

orbs: 
  node: circleci/node@5.0.2
  docker: circleci/docker@2.1.1

jobs:
  build-and-push:

    environments: 
      DOCKER_IMAGE: nhat/react-docker
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG

      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
workflows:
  my-pipeline:
    jobs:
      - build-and-push:
           filters: 
             branches: 
               only: 
                 - master
